name: Flutter Android Build

on:
  push:
    branches: [main] # Passe den Branch nach Bedarf an
  pull_request:
    branches: [main] # Passe den Branch nach Bedarf an

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # Oder spezifische Version mit 'flutter-version' angeben
        cache: true

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: '33.0.0'
        target: 'android-33'

    - name: Accept Android Licenses
      run: yes | sdkmanager --licenses

    - name: Get Flutter Packages
      run: flutter pub get

    - name: Build App Bundle
      run: flutter build appbundle --release

    - name: Upload App Bundle
      uses: actions/upload-artifact@v3
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab
