name: Flutter Android Build

on:
  push:
    branches: [main] # Passe den Branch nach Bedarf an
  pull_request:
    branches: [main] # Passe den Branch nach Bedarf an

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # Oder spezifische Version angeben
        channel: 'stable'
        cache: true
        android: true

    - name: Accept Android Licenses
      run: yes | flutter doctor --android-licenses

    - name: Get Flutter Packages
      run: flutter pub get

    - name: Build App Bundle
      run: flutter build appbundle --release

    - name: Upload App Bundle
      uses: actions/upload-artifact@v3
      with:
        name: app-release.aab
        path: build/app/outputs/bundle/release/app-release.aab
